import random
class Poker(object):
    def __init__ (self):
        cards = ['A', '2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K']
        suits = ['c', 'd', 'h', 's']
        self.deck = []
        for x in cards:
            for y in suits:
                self.deck.append((x, y))

    def hand(self):
        cards = ['A', 'K', 'Q', 'J', 'T', '9', '8', '7', '6', '5', '4', '3', '2']
        random.shuffle(self.deck)
        first_card = self.deck[0]
        second_card = self.deck[1]
        s = ""
        if first_card[0] == second_card[0]:
            s += first_card[0] + first_card[0]
            return s
        elif cards.index(first_card[0]) < cards.index(second_card[0]):
            s += first_card[0] + second_card[0]
        else:
            s += second_card[0] + first_card[0]
        if first_card[1] == second_card[1]:
            return s + 's'
        return s + 'o'

class Open(object):
    def __init__ (self):
        self.position = ''
        self.deck = Poker()

    def correct_play(self):
        self.position = random.choice(['SB', 'BU', 'CO', 'HJ', 'LJ'])
        if self.position == 'SB':
            dct = {'AA': 'red', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'purple', 'ATs': 'purple', 'A9s': 'purple', 'A8s': 'purple', 'A7s': 'red', 'A6s': 'orange', 'A5s': 'red', 'A4s': 'red', 'A3s': 'orange', 'A2s': 'orange', 'AKo': 'red', 'KK': 'red', 'KQs': 'purple', 'KJs': 'purple', 'KTs': 'purple', 'K9s': 'red', 'K8s': 'orange', 'K7s': 'orange', 'K6s': 'red', 'K5s': 'red', 'K4s': 'red', 'K3s': 'red', 'K2s': 'purple', 'AQo': 'red', 'KQo': 'red', 'QQ': 'red', 'QJs': 'purple', 'QTs': 'purple', 'Q9s': 'orange', 'Q8s': 'orange', 'Q7s': 'red', 'Q6s': 'red', 'Q5s': 'red', 'Q4s': 'red', 'Q3s': 'red', 'Q2s': 'yellow', 'AJo': 'red', 'KJo': 'red', 'QJo': 'red', 'JJ': 'red', 'JTs': 'purple', 'J9s': 'orange', 'J8s': 'orange', 'J7s': 'red', 'J6s': 'red', 'J5s': 'red', 'J4s': 'orange', 'J3s': 'green', 'J2s': 'white', 'ATo': 'red', 'KTo': 'orange', 'QTo': 'orange', 'JTo': 'red', 'TT': 'red', 'T9s': 'red', 'T8s': 'orange', 'T7s': 'red', 'T6s': 'purple', 'T5s': 'orange', 'T4s': 'green', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'red', 'K9o': 'red', 'Q9o': 'red', 'J9o': 'orange', 'T9o': 'red', '99': 'red', '98s': 'orange', '97s': 'red', '96s': 'red', '95s': 'orange', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'purple', 'K8o': 'orange', 'Q8o': 'white', 'J8o': 'light_blue', 'T8o': 'orange', '98o': 'red', '88': 'red', '87s': 'orange', '86s': 'red', '85s': 'purple', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'purple', 'K7o': 'white', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'white', '87o': 'red', '77': 'orange', '76s': 'red', '75s': 'red', '74s': 'red', '73s': 'grey', '72s': 'grey', 'A6o': 'red', 'K6o': 'white', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'light_blue', '66': 'orange', '65s': 'red', '64s': 'purple', '63s': 'light_blue', '62s': 'grey', 'A5o': 'red', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'light_blue', '55': 'orange', '54s': 'red', '53s': 'red', '52s': 'grey', 'A4o': 'orange', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'orange', '43s': 'light_blue', '42s': 'grey', 'A3o': 'green', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'orange', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'orange'}
            x = self.deck.hand()
            return ['You are the SB with {}. LJ folds, HJ folds, CO folds, BU folds. Correct play? '.format(x), dct[x]]
        elif self.position == 'BU':
            dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'purple', 'ATs': 'purple', 'A9s': 'purple', 'A8s': 'purple', 'A7s': 'purple', 'A6s': 'purple', 'A5s': 'purple', 'A4s': 'purple', 'A3s': 'purple', 'A2s': 'purple', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'purple', 'KJs': 'purple', 'KTs': 'purple', 'K9s': 'purple', 'K8s': 'purple', 'K7s': 'purple', 'K6s': 'purple', 'K5s': 'purple', 'K4s': 'purple', 'K3s': 'purple', 'K2s': 'purple', 'AQo': 'purple', 'KQo': 'purple', 'QQ': 'purple', 'QJs': 'purple', 'QTs': 'purple', 'Q9s': 'purple', 'Q8s': 'purple', 'Q7s': 'purple', 'Q6s': 'purple', 'Q5s': 'purple', 'Q4s': 'purple', 'Q3s': 'purple', 'Q2s': 'pink', 'AJo': 'purple', 'KJo': 'purple', 'QJo': 'purple', 'JJ': 'purple', 'JTs': 'purple', 'J9s': 'purple', 'J8s': 'purple', 'J7s': 'purple', 'J6s': 'purple', 'J5s': 'purple', 'J4s': 'blue', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'purple', 'KTo': 'purple', 'QTo': 'purple', 'JTo': 'purple', 'TT': 'purple', 'T9s': 'purple', 'T8s': 'purple', 'T7s': 'purple', 'T6s': 'purple', 'T5s': 'purple', 'T4s': 'blue', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'purple', 'K9o': 'purple', 'Q9o': 'purple', 'J9o': 'purple', 'T9o': 'purple', '99': 'purple', '98s': 'purple', '97s': 'purple', '96s': 'purple', '95s': 'purple', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'purple', 'K8o': 'pink', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'purple', '98o': 'purple', '88': 'purple', '87s': 'purple', '86s': 'purple', '85s': 'purple', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'purple', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'pink', '77': 'purple', '76s': 'purple', '75s': 'purple', '74s': 'blue', '73s': 'grey', '72s': 'grey', 'A6o': 'purple', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'pink', '66': 'purple', '65s': 'purple', '64s': 'purple', '63s': 'grey', '62s': 'grey', 'A5o': 'purple', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'purple', '54s': 'purple', '53s': 'purple', '52s': 'grey', 'A4o': 'purple', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'purple', '43s': 'grey', '42s': 'grey', 'A3o': 'pink', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'purple', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'purple'}
            x = self.deck.hand()
            return ['You are the BU with {}. LJ folds, HJ folds, CO folds. Correct play? '.format(x), dct[x]]
        elif self.position == 'CO':
            dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'purple', 'ATs': 'purple', 'A9s': 'purple', 'A8s': 'purple', 'A7s': 'purple', 'A6s': 'purple', 'A5s': 'purple', 'A4s': 'purple', 'A3s': 'purple', 'A2s': 'purple', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'purple', 'KJs': 'purple', 'KTs': 'purple', 'K9s': 'purple', 'K8s': 'purple', 'K7s': 'purple', 'K6s': 'purple', 'K5s': 'purple', 'K4s': 'purple', 'K3s': 'blue', 'K2s': 'grey', 'AQo': 'purple', 'KQo': 'purple', 'QQ': 'purple', 'QJs': 'purple', 'QTs': 'purple', 'Q9s': 'purple', 'Q8s': 'purple', 'Q7s': 'purple', 'Q6s': 'purple', 'Q5s': 'blue', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'purple', 'KJo': 'purple', 'QJo': 'purple', 'JJ': 'purple', 'JTs': 'purple', 'J9s': 'purple', 'J8s': 'purple', 'J7s': 'pink', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'purple', 'KTo': 'purple', 'QTo': 'purple', 'JTo': 'purple', 'TT': 'purple', 'T9s': 'purple', 'T8s': 'purple', 'T7s': 'purple', 'T6s': 'pink', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'purple', 'K9o': 'pink', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'blue', '99': 'purple', '98s': 'purple', '97s': 'purple', '96s': 'blue', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'blue', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'purple', '87s': 'purple', '86s': 'purple', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'purple', '76s': 'purple', '75s': 'blue', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'purple', '65s': 'purple', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'blue', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'purple', '54s': 'purple', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'purple', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'purple', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'blue'}
            x = self.deck.hand()
            return ['You are the CO with {}. LJ folds, HJ folds. Correct play? '.format(x), dct[x]]
        elif self.position == 'HJ':
            dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'purple', 'ATs': 'purple', 'A9s': 'purple', 'A8s': 'purple', 'A7s': 'purple', 'A6s': 'purple', 'A5s': 'purple', 'A4s': 'purple', 'A3s': 'purple', 'A2s': 'purple', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'purple', 'KJs': 'purple', 'KTs': 'purple', 'K9s': 'purple', 'K8s': 'purple', 'K7s': 'purple', 'K6s': 'purple', 'K5s': 'purple', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'purple', 'KQo': 'purple', 'QQ': 'purple', 'QJs': 'purple', 'QTs': 'purple', 'Q9s': 'purple', 'Q8s': 'purple', 'Q7s': 'grey', 'Q6s': 'pink', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'purple', 'KJo': 'purple', 'QJo': 'blue', 'JJ': 'purple', 'JTs': 'purple', 'J9s': 'purple', 'J8s': 'pink', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'purple', 'KTo': 'blue', 'QTo': 'blue', 'JTo': 'pink', 'TT': 'purple', 'T9s': 'purple', 'T8s': 'purple', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'blue', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'purple', '98s': 'purple', '97s': 'blue', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'purple', '87s': 'purple', '86s': 'pink', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'purple', '76s': 'purple', '75s': 'grey', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'purple', '65s': 'purple', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'purple', '54s': 'blue', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'purple', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'blue', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'blue'}
            x = self.deck.hand()
            return ['You are the HJ with {}. LJ folds. Correct play? '.format(x), dct[x]]
        else:
            dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'purple', 'ATs': 'purple', 'A9s': 'purple', 'A8s': 'purple', 'A7s': 'purple', 'A6s': 'purple', 'A5s': 'purple', 'A4s': 'purple', 'A3s': 'purple', 'A2s': 'purple', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'purple', 'KJs': 'purple', 'KTs': 'purple', 'K9s': 'purple', 'K8s': 'purple', 'K7s': 'blue', 'K6s': 'purple', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'purple', 'KQo': 'purple', 'QQ': 'purple', 'QJs': 'purple', 'QTs': 'purple', 'Q9s': 'purple', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'purple', 'KJo': 'blue', 'QJo': 'pink', 'JJ': 'purple', 'JTs': 'purple', 'J9s': 'purple', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'purple', 'KTo': 'pink', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'purple', 'T9s': 'purple', 'T8s': 'blue', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'purple', '98s': 'blue', '97s': 'grey', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'purple', '87s': 'pink', '86s': 'grey', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'purple', '76s': 'blue', '75s': 'grey', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'purple', '65s': 'blue', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'purple', '54s': 'pink', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'blue', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'pink', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'pink'}
            x = self.deck.hand()
            return ['You are the LJ with {}. Correct play? '.format(x), dct[x]]

class vsOpen(object):
    def __init__ (self):
        self.open = ''
        self.position = ''
        self.deck = Poker()

    def correct_play(self):
        self.open = random.choice(['BB', 'SB', 'BU', 'CO', 'HJ'])
        if self.open == 'BB':
            self.position = random.choice(['SB', 'BU', 'CO', 'HJ', 'LJ'])
            if self.position == 'SB':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'purple', 'ATs': 'yellow', 'A9s': 'green', 'A8s': 'green', 'A7s': 'yellow', 'A6s': 'green', 'A5s': 'red', 'A4s': 'red', 'A3s': 'orange', 'A2s': 'yellow', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'purple', 'KJs': 'red', 'KTs': 'orange', 'K9s': 'yellow', 'K8s': 'yellow', 'K7s': 'yellow', 'K6s': 'yellow', 'K5s': 'green', 'K4s': 'green', 'K3s': 'green', 'K2s': 'green', 'AQo': 'purple', 'KQo': 'yellow', 'QQ': 'purple', 'QJs': 'orange', 'QTs': 'yellow', 'Q9s': 'green', 'Q8s': 'green', 'Q7s': 'green', 'Q6s': 'green', 'Q5s': 'green', 'Q4s': 'green', 'Q3s': 'green', 'Q2s': 'green', 'AJo': 'yellow', 'KJo': 'green', 'QJo': 'green', 'JJ': 'purple', 'JTs': 'orange', 'J9s': 'yellow', 'J8s': 'green', 'J7s': 'yellow', 'J6s': 'green', 'J5s': 'green', 'J4s': 'yellow', 'J3s': 'yellow', 'J2s': 'yellow', 'ATo': 'green', 'KTo': 'green', 'QTo': 'green', 'JTo': 'green', 'TT': 'purple', 'T9s': 'red', 'T8s': 'yellow', 'T7s': 'green', 'T6s': 'yellow', 'T5s': 'yellow', 'T4s': 'orange', 'T3s': 'orange', 'T2s': 'orange', 'A9o': 'green', 'K9o': 'yellow', 'Q9o': 'yellow', 'J9o': 'yellow', 'T9o': 'yellow', '99': 'purple', '98s': 'red', '97s': 'yellow', '96s': 'green', '95s': 'yellow', '94s': 'orange', '93s': 'orange', '92s': 'orange', 'A8o': 'green', 'K8o': 'orange', 'Q8o': 'orange', 'J8o': 'orange', 'T8o': 'yellow', '98o': 'yellow', '88': 'orange', '87s': 'orange', '86s': 'green', '85s': 'green', '84s': 'green', '83s': 'grey', '82s': 'grey', 'A7o': 'yellow', 'K7o': 'light_blue', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'blue', '97o': 'light_blue', '87o': 'green', '77': 'yellow', '76s': 'red', '75s': 'green', '74s': 'green', '73s': 'green', '72s': 'grey', 'A6o': 'orange', 'K6o': 'orange', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'white', '76o': 'green', '66': 'yellow', '65s': 'red', '64s': 'green', '63s': 'green', '62s': 'green', 'A5o': 'yellow', 'K5o': 'pink', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'green', '55': 'green', '54s': 'orange', '53s': 'green', '52s': 'green', 'A4o': 'yellow', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'green', '44': 'green', '43s': 'green', '42s': 'green', 'A3o': 'orange', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'green', '32s': 'green', 'A2o': 'purple', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'green'}
                x = self.deck.hand()
                return ['You are the BB with {}. LJ folds, HJ folds, CO folds, BU folds, SB opens 3bb. Correct play? '.format(x), dct[x]]
            elif self.position == 'BU':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'purple', 'ATs': 'yellow', 'A9s': 'green', 'A8s': 'green', 'A7s': 'yellow', 'A6s': 'yellow', 'A5s': 'red', 'A4s': 'yellow', 'A3s': 'yellow', 'A2s': 'orange', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'purple', 'KJs': 'orange', 'KTs': 'yellow', 'K9s': 'green', 'K8s': 'green', 'K7s': 'yellow', 'K6s': 'orange', 'K5s': 'yellow', 'K4s': 'yellow', 'K3s': 'yellow', 'K2s': 'yellow', 'AQo': 'purple', 'KQo': 'orange', 'QQ': 'purple', 'QJs': 'yellow', 'QTs': 'orange', 'Q9s': 'green', 'Q8s': 'green', 'Q7s': 'green', 'Q6s': 'green', 'Q5s': 'green', 'Q4s': 'white', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'orange', 'KJo': 'orange', 'QJo': 'yellow', 'JJ': 'purple', 'JTs': 'orange', 'J9s': 'yellow', 'J8s': 'orange', 'J7s': 'orange', 'J6s': 'yellow', 'J5s': 'white', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'orange', 'KTo': 'orange', 'QTo': 'orange', 'JTo': 'orange', 'TT': 'purple', 'T9s': 'purple', 'T8s': 'yellow', 'T7s': 'yellow', 'T6s': 'red', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'yellow', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'light_blue', 'T9o': 'orange', '99': 'purple', '98s': 'orange', '97s': 'yellow', '96s': 'yellow', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'yellow', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'yellow', '87s': 'orange', '86s': 'yellow', '85s': 'light_blue', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'light_blue', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'green', '76s': 'red', '75s': 'green', '74s': 'white', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'green', '65s': 'orange', '64s': 'green', '63s': 'white', '62s': 'grey', 'A5o': 'light_blue', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'green', '54s': 'yellow', '53s': 'green', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'green', '43s': 'green', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'green', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'green'}
                x = self.deck.hand()
                return ['You are the BB with {}. LJ folds, HJ folds, CO folds, BU opens 3bb, SB folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'CO':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'yellow', 'ATs': 'yellow', 'A9s': 'green', 'A8s': 'green', 'A7s': 'green', 'A6s': 'yellow', 'A5s': 'orange', 'A4s': 'orange', 'A3s': 'yellow', 'A2s': 'orange', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'yellow', 'KJs': 'yellow', 'KTs': 'yellow', 'K9s': 'green', 'K8s': 'orange', 'K7s': 'yellow', 'K6s': 'orange', 'K5s': 'yellow', 'K4s': 'yellow', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'red', 'KQo': 'yellow', 'QQ': 'purple', 'QJs': 'yellow', 'QTs': 'orange', 'Q9s': 'yellow', 'Q8s': 'light_blue', 'Q7s': 'grey', 'Q6s': 'white', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'yellow', 'KJo': 'red', 'QJo': 'light_blue', 'JJ': 'purple', 'JTs': 'orange', 'J9s': 'orange', 'J8s': 'red', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'yellow', 'KTo': 'white', 'QTo': 'white', 'JTo': 'light_blue', 'TT': 'orange', 'T9s': 'orange', 'T8s': 'yellow', 'T7s': 'orange', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'green', '98s': 'yellow', '97s': 'green', '96s': 'yellow', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'green', '87s': 'yellow', '86s': 'green', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'green', '76s': 'yellow', '75s': 'green', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'green', '65s': 'yellow', '64s': 'green', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'green', '54s': 'yellow', '53s': 'green', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'green', '43s': 'white', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'green', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'green'}
                x = self.deck.hand()
                return ['You are the BB with {}. LJ folds, HJ folds, CO opens 3bb, BU folds, SB folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'HJ':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'green', 'ATs': 'yellow', 'A9s': 'green', 'A8s': 'yellow', 'A7s': 'green', 'A6s': 'green', 'A5s': 'orange', 'A4s': 'orange', 'A3s': 'orange', 'A2s': 'orange', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'yellow', 'KJs': 'yellow', 'KTs': 'green', 'K9s': 'orange', 'K8s': 'yellow', 'K7s': 'blue', 'K6s': 'red', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'yellow', 'KQo': 'orange', 'QQ': 'purple', 'QJs': 'orange', 'QTs': 'orange', 'Q9s': 'orange', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'yellow', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'red', 'JTs': 'orange', 'J9s': 'yellow', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'white', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'yellow', 'T9s': 'orange', 'T8s': 'yellow', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'green', '98s': 'yellow', '97s': 'yellow', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'green', '87s': 'orange', '86s': 'green', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'green', '76s': 'orange', '75s': 'green', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'green', '65s': 'orange', '64s': 'green', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'green', '54s': 'yellow', '53s': 'green', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'green', '43s': 'white', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'green', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'green'}
                x = self.deck.hand()
                return ['You are the BB with {}. LJ folds, HJ opens 3bb, CO folds, BU folds, SB folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'LJ':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'orange', 'AJs': 'green', 'ATs': 'green', 'A9s': 'yellow', 'A8s': 'yellow', 'A7s': 'yellow', 'A6s': 'green', 'A5s': 'orange', 'A4s': 'red', 'A3s': 'red', 'A2s': 'grey', 'AKo': 'red', 'KK': 'purple', 'KQs': 'red', 'KJs': 'yellow', 'KTs': 'yellow', 'K9s': 'orange', 'K8s': 'pink', 'K7s': 'pink', 'K6s': 'pink', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'yellow', 'KQo': 'light_blue', 'QQ': 'purple', 'QJs': 'orange', 'QTs': 'orange', 'Q9s': 'red', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'yellow', 'JTs': 'yellow', 'J9s': 'green', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'green', 'T9s': 'yellow', 'T8s': 'orange', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'green', '98s': 'yellow', '97s': 'white', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'green', '87s': 'orange', '86s': 'green', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'green', '76s': 'orange', '75s': 'white', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'green', '65s': 'orange', '64s': 'green', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'green', '54s': 'yellow', '53s': 'green', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'green', '43s': 'white', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'green', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'green'}
                x = self.deck.hand()
                return ['You are the BB with {}. LJ opens 3bb, HJ folds, CO folds, BU folds, SB folds. Correct play? '.format(x), dct[x]]
        elif self.open == 'SB':
            self.position = random.choice(['BU', 'CO', 'HJ', 'LJ'])
            if self.position == 'BU':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'red', 'ATs': 'orange', 'A9s': 'orange', 'A8s': 'yellow', 'A7s': 'orange', 'A6s': 'light_blue', 'A5s': 'purple', 'A4s': 'light_blue', 'A3s': 'grey', 'A2s': 'grey', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'purple', 'KJs': 'red', 'KTs': 'orange', 'K9s': 'red', 'K8s': 'grey', 'K7s': 'grey', 'K6s': 'grey', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'red', 'KQo': 'red', 'QQ': 'purple', 'QJs': 'orange', 'QTs': 'orange', 'Q9s': 'orange', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'purple', 'KJo': 'pink', 'QJo': 'grey', 'JJ': 'purple', 'JTs': 'red', 'J9s': 'purple', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'red', 'KTo': 'pink', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'purple', 'T9s': 'purple', 'T8s': 'red', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'red', '98s': 'red', '97s': 'grey', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'red', '87s': 'pink', '86s': 'grey', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'orange', '76s': 'pink', '75s': 'grey', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'orange', '65s': 'pink', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'light_blue', '54s': 'pink', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'white', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'white', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'white'}
                x = self.deck.hand()
                return ['You are the SB with {}. LJ folds, HJ folds, CO folds, BU opens 3bb. Correct play? '.format(x), dct[x]]
            elif self.position == 'CO':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'orange', 'ATs': 'orange', 'A9s': 'orange', 'A8s': 'grey', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'purple', 'A4s': 'purple', 'A3s': 'grey', 'A2s': 'grey', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'red', 'KJs': 'purple', 'KTs': 'red', 'K9s': 'blue', 'K8s': 'grey', 'K7s': 'grey', 'K6s': 'pink', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'purple', 'KQo': 'blue', 'QQ': 'purple', 'QJs': 'red', 'QTs': 'red', 'Q9s': 'grey', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'pink', 'KJo': 'pink', 'QJo': 'grey', 'JJ': 'purple', 'JTs': 'purple', 'J9s': 'blue', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'purple', 'T9s': 'pink', 'T8s': 'grey', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'red', '98s': 'grey', '97s': 'grey', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'light_blue', '87s': 'grey', '86s': 'grey', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'light_blue', '76s': 'pink', '75s': 'grey', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'light_blue', '65s': 'pink', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'grey', '54s': 'grey', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'grey', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'grey', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'grey'}
                x = self.deck.hand()
                return ['You are the SB with {}. LJ folds, HJ folds, CO opens 3bb, BU folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'HJ':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'orange', 'ATs': 'orange', 'A9s': 'grey', 'A8s': 'grey', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'blue', 'A4s': 'blue', 'A3s': 'grey', 'A2s': 'grey', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'red', 'KJs': 'red', 'KTs': 'red', 'K9s': 'grey', 'K8s': 'grey', 'K7s': 'grey', 'K6s': 'grey', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'red', 'KQo': 'pink', 'QQ': 'purple', 'QJs': 'purple', 'QTs': 'red', 'Q9s': 'grey', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'red', 'JTs': 'pink', 'J9s': 'grey', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'red', 'T9s': 'grey', 'T8s': 'grey', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'red', '98s': 'grey', '97s': 'grey', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'light_blue', '87s': 'grey', '86s': 'grey', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'light_blue', '76s': 'blue', '75s': 'grey', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'light_blue', '65s': 'blue', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'white', '54s': 'pink', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'grey', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'grey', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'grey'}
                x = self.deck.hand()
                return ['You are the SB with {}. LJ folds, HJ opens 3bb, CO folds, BU folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'LJ':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'red', 'ATs': 'red', 'A9s': 'pink', 'A8s': 'grey', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'blue', 'A4s': 'pink', 'A3s': 'grey', 'A2s': 'grey', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'purple', 'KJs': 'red', 'KTs': 'red', 'K9s': 'grey', 'K8s': 'grey', 'K7s': 'grey', 'K6s': 'grey', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'pink', 'KQo': 'grey', 'QQ': 'purple', 'QJs': 'blue', 'QTs': 'pink', 'Q9s': 'grey', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'red', 'JTs': 'grey', 'J9s': 'grey', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'red', 'T9s': 'grey', 'T8s': 'grey', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'light_blue', '98s': 'grey', '97s': 'grey', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'light_blue', '87s': 'grey', '86s': 'grey', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'light_blue', '76s': 'blue', '75s': 'grey', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'light_blue', '65s': 'blue', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'grey', '54s': 'pink', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'grey', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'grey', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'grey'}
                x = self.deck.hand()
                return ['You are the SB with {}. LJ opens 3bb, HJ folds, CO folds, BU folds. Correct play? '.format(x), dct[x]]
        elif self.open == 'BU':
            self.position = random.choice(['CO', 'HJ', 'LJ'])
            if self.position == 'CO':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'orange', 'ATs': 'green', 'A9s': 'green', 'A8s': 'orange', 'A7s': 'red', 'A6s': 'red', 'A5s': 'red', 'A4s': 'red', 'A3s': 'red', 'A2s': 'pink', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'red', 'KJs': 'orange', 'KTs': 'orange', 'K9s': 'red', 'K8s': 'pink', 'K7s': 'grey', 'K6s': 'pink', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'orange', 'KQo': 'red', 'QQ': 'purple', 'QJs': 'orange', 'QTs': 'orange', 'Q9s': 'blue', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'red', 'KJo': 'pink', 'QJo': 'grey', 'JJ': 'purple', 'JTs': 'orange', 'J9s': 'purple', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'blue', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'orange', 'T9s': 'orange', 'T8s': 'pink', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'orange', '98s': 'grey', '97s': 'grey', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'orange', '87s': 'grey', '86s': 'grey', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'orange', '76s': 'light_blue', '75s': 'grey', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'orange', '65s': 'light_blue', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'light_blue', '54s': 'light_blue', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'white', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'white', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'white'}
                x = self.deck.hand()
                return ['You are the BU with {}. LJ folds, HJ folds, CO opens 3bb. Correct play? '.format(x), dct[x]]
            elif self.position == 'HJ':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'red', 'AJs': 'green', 'ATs': 'green', 'A9s': 'orange', 'A8s': 'orange', 'A7s': 'red', 'A6s': 'red', 'A5s': 'red', 'A4s': 'red', 'A3s': 'red', 'A2s': 'grey', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'yellow', 'KJs': 'orange', 'KTs': 'yellow', 'K9s': 'purple', 'K8s': 'pink', 'K7s': 'pink', 'K6s': 'grey', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'orange', 'KQo': 'red', 'QQ': 'purple', 'QJs': 'red', 'QTs': 'orange', 'Q9s': 'grey', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'pink', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'orange', 'JTs': 'orange', 'J9s': 'grey', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'pink', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'orange', 'T9s': 'light_blue', 'T8s': 'grey', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'yellow', '98s': 'grey', '97s': 'grey', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'yellow', '87s': 'pink', '86s': 'grey', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'yellow', '76s': 'light_blue', '75s': 'grey', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'yellow', '65s': 'light_blue', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'white', '54s': 'light_blue', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'white', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'white', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'white'}
                x = self.deck.hand()
                return ['You are the BU with {}. LJ folds, HJ opens 3bb, CO folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'LJ':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'yellow', 'AJs': 'green', 'ATs': 'yellow', 'A9s': 'orange', 'A8s': 'light_blue', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'purple', 'A4s': 'red', 'A3s': 'blue', 'A2s': 'grey', 'AKo': 'red', 'KK': 'purple', 'KQs': 'yellow', 'KJs': 'orange', 'KTs': 'yellow', 'K9s': 'purple', 'K8s': 'pink', 'K7s': 'pink', 'K6s': 'pink', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'orange', 'KQo': 'blue', 'QQ': 'red', 'QJs': 'red', 'QTs': 'orange', 'Q9s': 'grey', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'orange', 'JTs': 'white', 'J9s': 'grey', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'yellow', 'T9s': 'white', 'T8s': 'grey', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'yellow', '98s': 'grey', '97s': 'grey', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'yellow', '87s': 'pink', '86s': 'grey', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'yellow', '76s': 'light_blue', '75s': 'grey', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'yellow', '65s': 'light_blue', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'white', '54s': 'light_blue', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'white', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'white', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'white'}
                x = self.deck.hand()
                return ['You are the BB with {}. LJ opens 3bb, HJ folds, CO folds. Correct play? '.format(x), dct[x]]
        elif self.open == 'CO':
            self.position = random.choice(['HJ', 'LJ'])
            if self.position == 'HJ':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'red', 'AJs': 'yellow', 'ATs': 'yellow', 'A9s': 'red', 'A8s': 'pink', 'A7s': 'grey', 'A6s': 'pink', 'A5s': 'purple', 'A4s': 'purple', 'A3s': 'blue', 'A2s': 'grey', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'orange', 'KJs': 'red', 'KTs': 'orange', 'K9s': 'pink', 'K8s': 'grey', 'K7s': 'pink', 'K6s': 'pink', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'red', 'KQo': 'blue', 'QQ': 'purple', 'QJs': 'red', 'QTs': 'red', 'Q9s': 'grey', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'orange', 'JTs': 'grey', 'J9s': 'grey', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'orange', 'T9s': 'grey', 'T8s': 'grey', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'orange', '98s': 'grey', '97s': 'grey', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'orange', '87s': 'pink', '86s': 'grey', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'light_blue', '76s': 'light_blue', '75s': 'grey', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'light_blue', '65s': 'light_blue', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'white', '54s': 'light_blue', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'white', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'grey', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'grey'}
                x = self.deck.hand()
                return ['You are the CO with {}. LJ folds, HJ opens 3bb. Correct play? '.format(x), dct[x]]
            elif self.position == 'LJ':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'orange', 'AJs': 'yellow', 'ATs': 'yellow', 'A9s': 'pink', 'A8s': 'grey', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'purple', 'A4s': 'purple', 'A3s': 'pink', 'A2s': 'grey', 'AKo': 'red', 'KK': 'purple', 'KQs': 'red', 'KJs': 'red', 'KTs': 'orange', 'K9s': 'pink', 'K8s': 'pink', 'K7s': 'pink', 'K6s': 'pink', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'red', 'KQo': 'pink', 'QQ': 'red', 'QJs': 'light_blue', 'QTs': 'light_blue', 'Q9s': 'grey', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'orange', 'JTs': 'grey', 'J9s': 'grey', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'orange', 'T9s': 'grey', 'T8s': 'grey', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'orange', '98s': 'grey', '97s': 'grey', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'light_blue', '87s': 'grey', '86s': 'grey', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'light_blue', '76s': 'light_blue', '75s': 'grey', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'light_blue', '65s': 'light_blue', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'grey', '54s': 'pink', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'grey', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'grey', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'grey'}
                x = self.deck.hand()
                return ['You are the CO with {}. LJ opens 3bb, HJ folds. Correct play? '.format(x), dct[x]]
        elif self.open == 'HJ':
            self.position = random.choice(['LJ'])
            if self.position == 'LJ':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'blue', 'ATs': 'blue', 'A9s': 'pink', 'A8s': 'grey', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'purple', 'A4s': 'blue', 'A3s': 'grey', 'A2s': 'grey', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'purple', 'KJs': 'purple', 'KTs': 'blue', 'K9s': 'grey', 'K8s': 'pink', 'K7s': 'pink', 'K6s': 'grey', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'blue', 'KQo': 'pink', 'QQ': 'purple', 'QJs': 'grey', 'QTs': 'grey', 'Q9s': 'grey', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'purple', 'JTs': 'grey', 'J9s': 'grey', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'J3s': 'grey', 'J2s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'purple', 'T9s': 'grey', 'T8s': 'grey', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'T3s': 'grey', 'T2s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'blue', '98s': 'grey', '97s': 'grey', '96s': 'grey', '95s': 'grey', '94s': 'grey', '93s': 'grey', '92s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'Q8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'pink', '87s': 'grey', '86s': 'grey', '85s': 'grey', '84s': 'grey', '83s': 'grey', '82s': 'grey', 'A7o': 'grey', 'K7o': 'grey', 'Q7o': 'grey', 'J7o': 'grey', 'T7o': 'grey', '97o': 'grey', '87o': 'grey', '77': 'pink', '76s': 'pink', '75s': 'grey', '74s': 'grey', '73s': 'grey', '72s': 'grey', 'A6o': 'grey', 'K6o': 'grey', 'Q6o': 'grey', 'J6o': 'grey', 'T6o': 'grey', '96o': 'grey', '86o': 'grey', '76o': 'grey', '66': 'pink', '65s': 'pink', '64s': 'grey', '63s': 'grey', '62s': 'grey', 'A5o': 'grey', 'K5o': 'grey', 'Q5o': 'grey', 'J5o': 'grey', 'T5o': 'grey', '95o': 'grey', '85o': 'grey', '75o': 'grey', '65o': 'grey', '55': 'grey', '54s': 'grey', '53s': 'grey', '52s': 'grey', 'A4o': 'grey', 'K4o': 'grey', 'Q4o': 'grey', 'J4o': 'grey', 'T4o': 'grey', '94o': 'grey', '84o': 'grey', '74o': 'grey', '64o': 'grey', '54o': 'grey', '44': 'grey', '43s': 'grey', '42s': 'grey', 'A3o': 'grey', 'K3o': 'grey', 'Q3o': 'grey', 'J3o': 'grey', 'T3o': 'grey', '93o': 'grey', '83o': 'grey', '73o': 'grey', '63o': 'grey', '53o': 'grey', '43o': 'grey', '33': 'grey', '32s': 'grey', 'A2o': 'grey', 'K2o': 'grey', 'Q2o': 'grey', 'J2o': 'grey', 'T2o': 'grey', '92o': 'grey', '82o': 'grey', '72o': 'grey', '62o': 'grey', '52o': 'grey', '42o': 'grey', '32o': 'grey', '22': 'grey'}
                x = self.deck.hand()
                return ['You are the HJ with {}. LJ opens 3bb. Correct play? '.format(x), dct[x]]

class vs3bet(object):
    def __init__(self):
        self.open = ''
        self.position = ''

    def correct_play(self):
        self.open = random.choice(['SB', 'BU', 'CO', 'HJ', 'LJ'])
        if self.open == 'SB':
            dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'purple', 'AJs': 'green', 'ATs': 'green', 'A9s': 'orange', 'A8s': 'green', 'A7s': 'green', 'A6s': 'yellow', 'A5s': 'orange', 'A4s': 'orange', 'A3s': 'orange', 'A2s': 'grey', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'green', 'KJs': 'red', 'KTs': 'green', 'K9s': 'orange', 'K8s': 'green', 'K7s': 'light_blue', 'K6s': 'pink', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'purple', 'KQo': 'red', 'QQ': 'purple', 'QJs': 'orange', 'QTs': 'green', 'Q9s': 'yellow', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'red', 'KJo': 'light_blue', 'QJo': 'grey', 'JJ': 'purple', 'JTs': 'yellow', 'J9s': 'yellow', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'ATo': 'blue', 'KTo': 'pink', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'purple', 'T9s': 'yellow', 'T8s': 'yellow', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'orange', '98s': 'red', '97s': 'grey', '96s': 'grey', '95s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'J8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'green', '87s': 'white', '86s': 'grey', '85s': 'grey', 'A7o': 'grey', '87o': 'grey', '77': 'yellow', '76s': 'white', '75s': 'grey', '74s': 'grey', 'A6o': 'grey', '76o': 'grey', '66': 'yellow', '65s': 'white', '64s': 'grey', '63s': 'grey', 'A5o': 'grey', '65o': 'grey', '55': 'yellow', '54s': 'white', '53s': 'grey', 'A4o': 'grey', '44': 'white', '43s': 'grey', '33': 'white', '22': 'grey'}
            x = random.choice(list(dct.keys()))
            return ['You are the SB with {}. Everyone folds to you, you open 3bb, BB raises 9bb. Correct play? '.format(x), dct[x]]
        elif self.open == 'BU':
            self.position = random.choice(['BB', 'SB'])
            if self.position == 'BB':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'yellow', 'AJs': 'green', 'ATs': 'green', 'A9s': 'green', 'A8s': 'yellow', 'A7s': 'yellow', 'A6s': 'pink', 'A5s': 'yellow', 'A4s': 'yellow', 'A3s': 'red', 'A2s': 'pink', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'green', 'KJs': 'green', 'KTs': 'green', 'K9s': 'yellow', 'K8s': 'red', 'K7s': 'grey', 'K6s': 'grey', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'orange', 'KQo': 'yellow', 'QQ': 'purple', 'QJs': 'yellow', 'QTs': 'green', 'Q9s': 'pink', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'orange', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'purple', 'JTs': 'green', 'J9s': 'yellow', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'ATo': 'pink', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'orange', 'T9s': 'green', 'T8s': 'white', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'green', '98s': 'white', '97s': 'grey', '96s': 'grey', '95s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'green', '87s': 'white', '86s': 'grey', '85s': 'grey', 'A7o': 'grey', '87o': 'grey', '77': 'yellow', '76s': 'white', '75s': 'grey', '74s': 'grey', 'A6o': 'grey', '66': 'yellow', '65s': 'white', '64s': 'grey', 'A5o': 'grey', '55': 'light_blue', '54s': 'white', '53s': 'grey', 'A4o': 'grey', '44': 'white', 'A3o': 'grey', '33': 'grey', '22': 'grey'}
                x = random.choice(list(dct.keys()))
                return ['You are the BU with {}. Everyone folds to you, you open 3bb, SB folds, BB raises 12bb. Correct play? '.format(x), dct[x]]
            elif self.position == 'SB':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'green', 'AJs': 'green', 'ATs': 'green', 'A9s': 'yellow', 'A8s': 'yellow', 'A7s': 'light_blue', 'A6s': 'pink', 'A5s': 'green', 'A4s': 'yellow', 'A3s': 'orange', 'A2s': 'pink', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'green', 'KJs': 'green', 'KTs': 'green', 'K9s': 'yellow', 'K8s': 'light_blue', 'K7s': 'pink', 'K6s': 'grey', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'K2s': 'grey', 'AQo': 'yellow', 'KQo': 'yellow', 'QQ': 'purple', 'QJs': 'yellow', 'QTs': 'green', 'Q9s': 'orange', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'Q4s': 'grey', 'Q3s': 'grey', 'Q2s': 'grey', 'AJo': 'yellow', 'KJo': 'pink', 'QJo': 'grey', 'JJ': 'purple', 'JTs': 'green', 'J9s': 'green', 'J8s': 'grey', 'J7s': 'grey', 'J6s': 'grey', 'J5s': 'grey', 'J4s': 'grey', 'ATo': 'pink', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'orange', 'T9s': 'green', 'T8s': 'white', 'T7s': 'grey', 'T6s': 'grey', 'T5s': 'grey', 'T4s': 'grey', 'A9o': 'grey', 'K9o': 'grey', 'Q9o': 'grey', 'J9o': 'grey', 'T9o': 'grey', '99': 'green', '98s': 'green', '97s': 'grey', '96s': 'grey', '95s': 'grey', 'A8o': 'grey', 'K8o': 'grey', 'T8o': 'grey', '98o': 'grey', '88': 'green', '87s': 'white', '86s': 'grey', '85s': 'grey', 'A7o': 'grey', '87o': 'grey', '77': 'yellow', '76s': 'green', '75s': 'grey', '74s': 'grey', 'A6o': 'grey', '66': 'yellow', '65s': 'green', '64s': 'grey', 'A5o': 'grey', '55': 'yellow', '54s': 'white', '53s': 'grey', 'A4o': 'grey', '44': 'light_blue', 'A3o': 'grey', '33': 'white', '22': 'white'}
                x = random.choice(list(dct.keys()))
                return ['You are the BU with {}. Everyone folds to you, you open 3bb, SB raises 12bb, BB folds. Correct play? '.format(x), dct[x]]
        elif self.open == 'CO':
            self.position = random.choice(['BU', 'BB', 'SB'])
            if self.position == 'BU':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'green', 'AJs': 'green', 'ATs': 'orange', 'A9s': 'orange', 'A8s': 'white', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'purple', 'A4s': 'grey', 'A3s': 'grey', 'A2s': 'grey', 'AKo': 'purple', 'KK': 'purple', 'KQs': 'green', 'KJs': 'purple', 'KTs': 'red', 'K9s': 'light_blue', 'K8s': 'grey', 'K7s': 'grey', 'K6s': 'grey', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'AQo': 'red', 'KQo': 'pink', 'QQ': 'purple', 'QJs': 'orange', 'QTs': 'light_blue', 'Q9s': 'grey', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'AJo': 'pink', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'purple', 'JTs': 'orange', 'J9s': 'grey', 'J8s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'orange', 'T9s': 'white', 'T8s': 'grey', 'T7s': 'grey', 'A9o': 'grey', 'T9o': 'grey', '99': 'orange', '98s': 'white', '97s': 'grey', '96s': 'grey', 'A8o': 'grey', '88': 'orange', '87s': 'white', '86s': 'grey', '77': 'light_blue', '76s': 'white', '75s': 'grey', '66': 'white', '65s': 'white', 'A5o': 'grey', '55': 'white', '54s': 'white', '44': 'white', '33': 'white', '22': 'white'}
                x = random.choice(list(dct.keys()))
                return ['You are the CO with {}. Everyone folds to you, you open 3bb, BU raises 9bb, SB folds, BB folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'BB':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'green', 'AJs': 'green', 'ATs': 'green', 'A9s': 'green', 'A8s': 'orange', 'A7s': 'pink', 'A6s': 'grey', 'A5s': 'green', 'A4s': 'light_blue', 'A3s': 'blue', 'A2s': 'purple', 'AKo': 'orange', 'KK': 'purple', 'KQs': 'green', 'KJs': 'green', 'KTs': 'green', 'K9s': 'light_blue', 'K8s': 'grey', 'K7s': 'grey', 'K6s': 'pink', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'AQo': 'orange', 'KQo': 'pink', 'QQ': 'purple', 'QJs': 'yellow', 'QTs': 'green', 'Q9s': 'grey', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'AJo': 'grey', 'KJo': 'pink', 'QJo': 'grey', 'JJ': 'yellow', 'JTs': 'green', 'J9s': 'grey', 'J8s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'green', 'T9s': 'grey', 'T8s': 'grey', 'T7s': 'grey', 'A9o': 'grey', 'T9o': 'grey', '99': 'white', '98s': 'grey', '97s': 'grey', '96s': 'grey', 'A8o': 'grey', '88': 'light_blue', '87s': 'white', '86s': 'grey', '77': 'light_blue', '76s': 'white', '75s': 'grey', '66': 'white', '65s': 'white', 'A5o': 'grey', '55': 'white', '54s': 'white', '44': 'white', '33': 'white', '22': 'grey'}
                x = random.choice(list(dct.keys()))
                return ['You are the CO with {}. Everyone folds to you, you open 3bb, BU folds, SB folds, BB raises 12bb. Correct play? '.format(x), dct[x]]
            elif self.position == 'SB':
                dct = {'AA': 'purple', 'AKs': 'red', 'AQs': 'green', 'AJs': 'green', 'ATs': 'green', 'A9s': 'white', 'A8s': 'pink', 'A7s': 'pink', 'A6s': 'grey', 'A5s': 'orange', 'A4s': 'blue', 'A3s': 'pink', 'A2s': 'grey', 'AKo': 'orange', 'KK': 'purple', 'KQs': 'green', 'KJs': 'green', 'KTs': 'yellow', 'K9s': 'pink', 'K8s': 'pink', 'K7s': 'grey', 'K6s': 'grey', 'K5s': 'grey', 'K4s': 'grey', 'K3s': 'grey', 'AQo': 'yellow', 'KQo': 'pink', 'QQ': 'purple', 'QJs': 'white', 'QTs': 'white', 'Q9s': 'grey', 'Q8s': 'grey', 'Q7s': 'grey', 'Q6s': 'grey', 'Q5s': 'grey', 'AJo': 'pink', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'orange', 'JTs': 'green', 'J9s': 'grey', 'J8s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'yellow', 'T9s': 'white', 'T8s': 'grey', 'T7s': 'grey', 'A9o': 'grey', 'T9o': 'grey', '99': 'white', '98s': 'grey', '97s': 'grey', '96s': 'grey', 'A8o': 'grey', '88': 'white', '87s': 'white', '86s': 'grey', '77': 'white', '76s': 'white', '75s': 'grey', '66': 'white', '65s': 'white', 'A5o': 'grey', '55': 'white', '54s': 'white', '44': 'white', '33': 'white', '22': 'grey'}
                x = random.choice(list(dct.keys()))
                return ['You are the CO with {}. Everyone folds to you, you open 3bb, BU folds, SB raises 12bb, BB folds. Correct play? '.format(x), dct[x]]

        elif self.open == 'HJ':
            self.position = random.choice(['CO', 'BU', 'BB', 'SB'])
            if self.position == 'CO':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'yellow', 'AJs': 'yellow', 'ATs': 'yellow', 'A9s': 'white', 'A8s': 'grey', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'red', 'A4s': 'light_blue', 'A3s': 'pink', 'A2s': 'grey', 'AKo': 'red', 'KK': 'purple', 'KQs': 'red', 'KJs': 'orange', 'KTs': 'orange', 'K9s': 'blue', 'K8s': 'grey', 'K7s': 'grey', 'K6s': 'grey', 'K5s': 'grey', 'AQo': 'red', 'KQo': 'grey', 'QQ': 'purple', 'QJs': 'light_blue', 'QTs': 'white', 'Q9s': 'grey', 'Q8s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'orange', 'JTs': 'green', 'J9s': 'grey', 'J8s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'yellow', 'T9s': 'white', 'T8s': 'grey', 'A9o': 'grey', '99': 'yellow', '98s': 'white', '97s': 'grey', '88': 'light_blue', '87s': 'white', '77': 'white', '76s': 'light_blue', '66': 'white', '65s': 'yellow', '55': 'white', '54s': 'green', '44': 'white', '33': 'green', '22': 'green'}
                x = random.choice(list(dct.keys()))
                return ['You are the HJ with {}. LJ folds, you open 3bb, CO raises 9bb, BU folds, SB folds, BB folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'BU':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'green', 'AJs': 'green', 'ATs': 'yellow', 'A9s': 'white', 'A8s': 'grey', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'blue', 'A4s': 'grey', 'A3s': 'grey', 'A2s': 'grey', 'AKo': 'red', 'KK': 'purple', 'KQs': 'orange', 'KJs': 'purple', 'KTs': 'red', 'K9s': 'grey', 'K8s': 'grey', 'K7s': 'grey', 'K6s': 'grey', 'K5s': 'grey', 'AQo': 'red', 'KQo': 'grey', 'QQ': 'purple', 'QJs': 'light_blue', 'QTs': 'light_blue', 'Q9s': 'grey', 'Q8s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'red', 'JTs': 'white', 'J9s': 'grey', 'J8s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'yellow', 'T9s': 'grey', 'T8s': 'grey', 'A9o': 'grey', '99': 'yellow', '98s': 'grey', '97s': 'grey', '88': 'light_blue', '87s': 'grey', '77': 'white', '76s': 'light_blue', '66': 'white', '65s': 'white', '55': 'white', '54s': 'white', '44': 'white', '33': 'white', '22': 'green'}
                x = random.choice(list(dct.keys()))
                return ['You are the HJ with {}. LJ folds, you open 3bb, CO folds, BU raises 9bb, SB folds, BB folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'SB':
                dct = {'AA': 'purple', 'AKs': 'red', 'AQs': 'green', 'AJs': 'yellow', 'ATs': 'yellow', 'A9s': 'light_blue', 'A8s': 'light_blue', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'yellow', 'A4s': 'light_blue', 'A3s': 'pink', 'A2s': 'pink', 'AKo': 'yellow', 'KK': 'purple', 'KQs': 'yellow', 'KJs': 'orange', 'KTs': 'orange', 'K9s': 'pink', 'K8s': 'pink', 'K7s': 'pink', 'K6s': 'pink', 'K5s': 'grey', 'AQo': 'light_blue', 'KQo': 'grey', 'QQ': 'yellow', 'QJs': 'white', 'QTs': 'white', 'Q9s': 'grey', 'Q8s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'yellow', 'JTs': 'white', 'J9s': 'grey', 'J8s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'yellow', 'T9s': 'white', 'T8s': 'grey', 'A9o': 'grey', '99': 'yellow', '98s': 'grey', '97s': 'grey', '88': 'light_blue', '87s': 'white', '77': 'white', '76s': 'white', '66': 'white', '65s': 'white', '55': 'white', '54s': 'white', '44': 'white', '33': 'white', '22': 'white'}
                x = random.choice(list(dct.keys()))
                return ['You are the HJ with {}. LJ folds, you open 3bb, CO folds, BU folds, SB raises 12bb, BB folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'BB':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'green', 'AJs': 'green', 'ATs': 'green', 'A9s': 'light_blue', 'A8s': 'light_blue', 'A7s': 'pink', 'A6s': 'grey', 'A5s': 'yellow', 'A4s': 'orange', 'A3s': 'pink', 'A2s': 'grey', 'AKo': 'yellow', 'KK': 'purple', 'KQs': 'green', 'KJs': 'orange', 'KTs': 'orange', 'K9s': 'pink', 'K8s': 'grey', 'K7s': 'grey', 'K6s': 'grey', 'K5s': 'grey', 'AQo': 'light_blue', 'KQo': 'grey', 'QQ': 'yellow', 'QJs': 'white', 'QTs': 'white', 'Q9s': 'grey', 'Q8s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'yellow', 'JTs': 'grey', 'J9s': 'grey', 'J8s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'JTo': 'grey', 'TT': 'yellow', 'T9s': 'white', 'T8s': 'grey', 'A9o': 'grey', '99': 'light_blue', '98s': 'grey', '97s': 'grey', '88': 'light_blue', '87s': 'white', '77': 'white', '76s': 'white', '66': 'white', '65s': 'white', '55': 'white', '54s': 'grey', '44': 'white', '33': 'grey', '22': 'grey'}
                x = random.choice(list(dct.keys()))
                return ['You are the HJ with {}. LJ folds, you open 3bb, CO folds, BU folds, SB folds, BB raises 12bb. Correct play? '.format(x), dct[x]]

        elif self.open == 'LJ':
            self.position = random.choice(['HJ', 'CO', 'BU', 'BB', 'SB'])
            if self.position == 'HJ':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'yellow', 'AJs': 'yellow', 'ATs': 'light_blue', 'A9s': 'grey', 'A8s': 'grey', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'red', 'A4s': 'light_blue', 'A3s': 'pink', 'A2s': 'grey', 'AKo': 'red', 'KK': 'purple', 'KQs': 'red', 'KJs': 'orange', 'KTs': 'orange', 'K9s': 'grey', 'K8s': 'grey', 'K7s': 'grey', 'K6s': 'grey', 'AQo': 'blue', 'KQo': 'grey', 'QQ': 'red', 'QJs': 'grey', 'QTs': 'grey', 'Q9s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'yellow', 'JTs': 'white', 'J9s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'TT': 'yellow', 'T9s': 'white', 'T8s': 'grey', '99': 'light_blue', '98s': 'white', '88': 'light_blue', '87s': 'yellow', '77': 'white', '76s': 'orange', '66': 'white', '65s': 'yellow', '55': 'white', '54s': 'green', '44': 'green', '33': 'green', '22': 'green'}
                x = random.choice(list(dct.keys()))
                return ['You are the LJ with {}. You open 3bb, HJ raises 9bb, CO folds, BU folds, SB folds, BB folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'CO':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'yellow', 'AJs': 'yellow', 'ATs': 'yellow', 'A9s': 'grey', 'A8s': 'grey', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'red', 'A4s': 'light_blue', 'A3s': 'pink', 'A2s': 'grey', 'AKo': 'red', 'KK': 'purple', 'KQs': 'red', 'KJs': 'orange', 'KTs': 'orange', 'K9s': 'grey', 'K8s': 'grey', 'K7s': 'grey', 'K6s': 'grey', 'AQo': 'light_blue', 'KQo': 'grey', 'QQ': 'red', 'QJs': 'white', 'QTs': 'white', 'Q9s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'yellow', 'JTs': 'white', 'J9s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'TT': 'yellow', 'T9s': 'white', 'T8s': 'grey', '99': 'light_blue', '98s': 'white', '88': 'light_blue', '87s': 'green', '77': 'white', '76s': 'orange', '66': 'white', '65s': 'yellow', '55': 'white', '54s': 'green', '44': 'green', '33': 'green', '22': 'green'}
                x = random.choice(list(dct.keys()))
                return ['You are the LJ with {}. You open 3bb, HJ folds, CO raises 9bb, BU folds, SB folds, BB folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'BU':
                dct = {'AA': 'purple', 'AKs': 'purple', 'AQs': 'green', 'AJs': 'yellow', 'ATs': 'yellow', 'A9s': 'light_blue', 'A8s': 'light_blue', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'red', 'A4s': 'pink', 'A3s': 'grey', 'A2s': 'grey', 'AKo': 'red', 'KK': 'purple', 'KQs': 'orange', 'KJs': 'blue', 'KTs': 'blue', 'K9s': 'grey', 'K8s': 'grey', 'K7s': 'grey', 'K6s': 'grey', 'AQo': 'blue', 'KQo': 'grey', 'QQ': 'red', 'QJs': 'grey', 'QTs': 'grey', 'Q9s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'orange', 'JTs': 'grey', 'J9s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'TT': 'yellow', 'T9s': 'white', 'T8s': 'grey', '99': 'light_blue', '98s': 'grey', '88': 'white', '87s': 'white', '77': 'white', '76s': 'light_blue', '66': 'white', '65s': 'white', '55': 'white', '54s': 'white', '44': 'white', '33': 'white', '22': 'green'}
                x = random.choice(list(dct.keys()))
                return ['You are the LJ with {}. You open 3bb, HJ folds, CO folds, BU raises 9bb, SB folds, BB folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'SB':
                dct = {'AA': 'purple', 'AKs': 'red', 'AQs': 'green', 'AJs': 'yellow', 'ATs': 'yellow', 'A9s': 'light_blue', 'A8s': 'light_blue', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'orange', 'A4s': 'light_blue', 'A3s': 'pink', 'A2s': 'pink', 'AKo': 'yellow', 'KK': 'red', 'KQs': 'yellow', 'KJs': 'light_blue', 'KTs': 'light_blue', 'K9s': 'pink', 'K8s': 'pink', 'K7s': 'grey', 'K6s': 'grey', 'AQo': 'pink', 'KQo': 'grey', 'QQ': 'green', 'QJs': 'grey', 'QTs': 'grey', 'Q9s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'yellow', 'JTs': 'white', 'J9s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'TT': 'yellow', 'T9s': 'white', 'T8s': 'grey', '99': 'light_blue', '98s': 'grey', '88': 'light_blue', '87s': 'green', '77': 'white', '76s': 'white', '66': 'white', '65s': 'white', '55': 'grey', '54s': 'green', '44': 'white', '33': 'white', '22': 'white'}
                x = random.choice(list(dct.keys()))
                return ['You are the LJ with {}. You open 3bb, HJ folds, CO folds, BU folds, SB raises 12bb, BB folds. Correct play? '.format(x), dct[x]]
            elif self.position == 'BB':
                dct = {'AA': 'purple', 'AKs': 'red', 'AQs': 'green', 'AJs': 'yellow', 'ATs': 'yellow', 'A9s': 'light_blue', 'A8s': 'light_blue', 'A7s': 'grey', 'A6s': 'grey', 'A5s': 'orange', 'A4s': 'light_blue', 'A3s': 'pink', 'A2s': 'pink', 'AKo': 'yellow', 'KK': 'red', 'KQs': 'yellow', 'KJs': 'light_blue', 'KTs': 'light_blue', 'K9s': 'pink', 'K8s': 'pink', 'K7s': 'grey', 'K6s': 'grey', 'AQo': 'pink', 'KQo': 'grey', 'QQ': 'green', 'QJs': 'grey', 'QTs': 'grey', 'Q9s': 'grey', 'AJo': 'grey', 'KJo': 'grey', 'QJo': 'grey', 'JJ': 'yellow', 'J9s': 'grey', 'ATo': 'grey', 'KTo': 'grey', 'QTo': 'grey', 'TT': 'yellow', 'T9s': 'white', 'T8s': 'grey', '99': 'light_blue', '98s': 'grey', '88': 'light_blue', '87s': 'green', '77': 'white', '76s': 'white', '66': 'white', '65s': 'white', '55': 'grey', '54s': 'green', '44': 'white', '33': 'white', '22': 'white'}
                x = random.choice(list(dct.keys()))
                return ['You are the LJ with {}. You open 3bb, HJ folds, CO folds, BU folds, SB folds, BB raises 12bb. Correct play? '.format(x), dct[x]]

key = {'red':[75, 25, 0], 'purple': [100, 0, 0], 'orange': [50, 50, 0], 'yellow': [25, 75, 0], 'green':[0,100,0], 'pink':[25, 0, 75], 'blue':[50,0,50], 'white':[0,50,50], 'light_blue':[25,25,50], 'grey':[0,0,100]}

test = Poker()
openings = ['open', 'vsOpen', 'vs3bet', 'vs4bet']

vsOpen_ = vsOpen()
Open_ = Open()
vs3bet_ = vs3bet()
while True:
    tmp = random.choice(['Open', 'vsOpen', 'vs3bet'])
    if tmp == 'Open':
        tmp = Open_.correct_play()
    elif tmp == 'vsOpen':
        tmp = vsOpen_.correct_play()
    elif tmp == 'vs3bet':
        tmp = vs3bet_.correct_play()
    x = input(tmp[0])
    answer = 0
    if x == 'R' or x == 'r':
        answer = 0
    elif x == 'C' or x == 'c':
        answer = 1
    elif x == 'F' or x == 'f':
        answer = 2
    if key[tmp[1]][answer] == 0:
        s = 'Incorrect dumbass! '
    else:
        s = 'Correct. '
    t = []
    for x in range(len(key[tmp[1]])):
        if x == 0 and key[tmp[1]][0] != 0:
            t.append('{}% Raise'.format(key[tmp[1]][0]))
        elif x == 1 and key[tmp[1]][1] != 0:
            t.append('{}% Call'.format(key[tmp[1]][1]))
        elif x == 2 and key[tmp[1]][2] != 0:
            t.append('{}% Fold'.format(key[tmp[1]][2]))
    s += ', '.join(t) + '.'
    print(s)
